#include <stdio.h>

/**
 * main - prints Each new term in the Fibonacci sequence 
 * @void: nothing .
 *
 * Description:Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2.
 * Return: 0 Always.
 */

int main(void)
{
	int q = 0;
	long i = 1, j = 2;
	long sum = j;

	while (j + i < 500000)
	{
		j += i;
	       if (j % 2 == 0)
	       {
		       sum += j;
		       i = j - i;
	       }
			++q;	       
	}
	printf("%ld\n", sum);
	return (0);
}
