#include <stdio.h>

/**
 * main - prints Each new term in the Fibonacci sequence 
 * @void: nothing .
 *
 * Description:Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2.
 * Return: 0 Always.
 */

int main(void)
{
	int a, i, nx, sum;

	a = 1;
	i = 0; 
	nx = 0;
	sum = 0;

	while (nx < 4000000)
	{
		nx = a + i;
		i = a;
		b = nx;
		if (nx % 2 == 0)
			sum += nx;
	}
	printf("%d\n", sum);
	return (0);


}
