#include <stdio.h>

/**
 * main - prints Each new term in the Fibonacci sequence 
 * @void: nothing .
 *
 * Description:Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2.
 * Return: 0 Always.
 */

int main(void)
{
int i = 0, j = 1, next = 0;
int sum = 0;

while (next < 4000000)
{
next = i + j;
i = j;
j = next;
if (next % 2 == 0)
sum += next;
}
printf("%d\n", sum);
return (0);


}
